#index:
#    path: /
#    controller: App\Controller\DefaultController::index

registration:
    path: /jwt/register
    controller: App\Controller\AuthController::register

login_check:
    path:     /jwt/login
    methods:  [POST]
